### ISSUE TITLE
[Bug report] create-vuepress is not working properly

### ISSUE THREAD

**Issue by ditoukanyun** [vuepress/ecosystem#202]
### Description

pnpm create vuepress vuepress-starter

 "docs:dev": "vuepress dev docs",

![image](https://github.com/vuepress/core/assets/36726434/a65affc4-7dec-4d07-b1f1-b7b718f7fef6)

### Reproduction

1

### Used Package Manager

pnpm

### System Info

```shell
"vuepress": "^2.0.0-rc.7",
```

**Comment by Mister-Hope** [comment]
Yes, because lerna won't bump that package unless it's code has been changed.

@meteorlxy @pengzhanbo any ideas to  have its version bumped while.ensure core and ecosystem are not misaligned (while core just released a new version)?

**Comment by pengzhanbo** [comment]
@meteorlxy @Mister-Hope 

We can use [pacote](https://github.com/npm/pacote#readme) to check the latest version numbers of `vuepress@next` and `@vuepress/*@next`, and then insert them into `package.json`. This way, `create-vuepress` will not be strongly coupled with the versions.

Just like this:
```ts
const res = await pacote.packument('vuepress')
const distTags = res['dist-tags']
console.log(distTags['next'])
```

**Comment by Mister-Hope** [comment]
> Alternatively,wen can dynamically install vuepress@next, @vuepress/*@next, and other packages using install-pkg after generating the project to ensure that the installed package contents are always up-to-date.

We couldn't.  Like I said before, there could be times where core release a new version and the ecosystem has not suport it.

The helper should always try to use core version that ecosystem supports.

**Comment by Mister-Hope** [comment]
The simplest hack could be announcing  all the needed packages as optional peers and reference them as workspace,  So that the package could be automatically bumped and get the correct version in this repo.

**Comment by pengzhanbo** [comment]
The `vuepress/core` repository uses the combination of `bumpp + pnpm publish -r` to ensure that all packages within the repository have the same version number. Perhaps `vuepress/ecosystem` should also consider implementing having all packages within the repository share the same version number.

Subsequently, we can utilize this approach to use [pacote](https://github.com/npm/pacote#readme) to retrieve package information for `@vuepress/theme-default`, including its version number and the `vuepress` version number from its `peer deps`, in order to determine the versions of other packages that should be installed.

**Comment by haonan66** [comment]
我也遇到这个问题了，请问要怎么解决?

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/commit/e8da8b81a9b515e4a5b0838468be78724ffe2120
