### ISSUE TITLE
[Bug report] commentService  do not display

### ISSUE THREAD

**Issue by Nuyoah0525** [vuepress/ecosystem#210]
### Description

  "vuepress": "2.0.0-rc.14"
   "@vuepress/plugin-comment": "^2.0.0-rc.37",
content：
<template>
  <ParentLayout>
    <template #page-bottom>
      <span>footer</span>

      <CommentService />
    </template>
  </ParentLayout>
</template>

problem:  
only   <span>footer</span> display  
  <CommentService /> do not work

### Reproduction

https://gitee.com/zyh0525/yh-blog/tree/master

### Used Package Manager

yarn

### System Info

```shell
"vuepress": "2.0.0-rc.14"
```

**Comment by Mister-Hope** [comment]
I am busy real life now so I do not have  time to fully test this repro on my laptop  In the next coming days,  So my suggestion is you should confirm that you can visit the giscus service in your local network as you are providing a gitee repo and I'm assuming you are in mainland China

If you can't then it's not about the plugin,  I don't think there are actually any bugs  Because at least theme hope is working fine
