### ISSUE TITLE
[Bug report] Code block performs poorly when its bg color is similar to the theme's bg color.

### ISSUE THREAD

**Issue by pengzhanbo** [vuepress/ecosystem#245]
### Description

Currently, code highlighting plugins support applying different background colors to code blocks based on various highlighting themes. However, when the background color of the code block is similar to or even the same as the theme background color, it becomes difficult to distinguish the code block from other content, resulting in a poor visual presentation.

For example, when using `@vuepress/plugin-shiki` with `github-light`, the background color of the code blocks is `#fff`, which is consistent with the theme's background color. The appearance at this time is as follows:

![QQ_1726216631563](https://github.com/user-attachments/assets/f741a385-0a15-42af-afde-d228db5ccc60)

![QQ_1726216662506](https://github.com/user-attachments/assets/5623eb78-e37c-4f40-840c-a51e952aa735)

### Reproduction

-

### Used Package Manager

npm

### System Info

```shell
-
```

**Comment by pengzhanbo** [comment]
We need solutions for situations like this:
1. How to identify when such problems occur;
2. Change the background color of the code block or add a border.

**Comment by Mister-Hope** [comment]
Though  shiki plugin may understand the background color of each theme, but it still can not understand how `--vp-c-bg` differs with shiki background.

In a pervious patch, we already set `--code-c-bg` with higher priority, so that developers and users should be able to override code block color to another value, or add border with extra css.

So I don't think there is anything that a plugin should do.
