### ISSUE TITLE
[Bug report] Hydration attribute mismatch with theme-default

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/ecosystem#282]
### Description

See console

### Reproduction

https://ecosystem.vuejs.press/

### Used Package Manager

pnpm

### System Info

```shell
.
```

**Comment by Mister-Hope** [comment]
@pengzhanbo Need some help here, I am not finding the reason myself

**Comment by pengzhanbo** [comment]
```log
<a aria-label="Theme Guidelines" class="route-link auto-link" href="/themes/guidelines"><!---->Theme Guidelines<!----></a>

  - rendered on server: href="/themes/guidelines"
  - expected on client: href="/themes/guidelines.html"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch.
```

The `<AutoLink>` component has inconsistent results between SSR and client-side rendering when handling the `href` attribute.

**Comment by pengzhanbo** [comment]
But when I built it locally and checked the SSR output, it turned out to be normal.

**Comment by Mister-Hope** [comment]
Yes, and that's why I am confusing

**Comment by pengzhanbo** [comment]
I checked the build process in `workflows/release.yml`, and in `jobs deploy-docs`, it executes `pnpm build` instead of `pnpm bundle`. Is there a problem with that? I also checked the output on the `netlify` branch. In the [`index.html`](https://github.com/vuepress/ecosystem/blob/netlify/index.html#L40) of the branch, the build output is normal. However, the source code online is inconsistent with the branch source code.

**Comment by Mister-Hope** [comment]
Fixed. Pretty URLs is default on for all Netlify sites, and should be manually toggled to 'off', a manually redeploy is needed to sync the configuration changes.

![image](https://github.com/user-attachments/assets/8e5e6b7c-a5b7-48c2-a517-88d9c4f91614)
